#!/bin/bash
# Session Context Hook
# 이벤트: SessionStart
# 용도: 세션 시작 시 프로젝트 컨텍스트 자동 로드

set -e

# stdin에서 JSON 입력 읽기
INPUT=$(cat)

# 프로젝트 루트 디렉토리 확인
PROJECT_ROOT=$(pwd)
CONTEXT_FILE="$PROJECT_ROOT/.claude/context/session_context.md"

# 컨텍스트 디렉토리 생성
mkdir -p "$PROJECT_ROOT/.claude/context"

# 현재 날짜
TODAY=$(date +%Y-%m-%d)
WEEKDAY=$(date +%A)

# 최근 커밋 정보
RECENT_COMMITS=$(git log --oneline -5 2>/dev/null || echo "No git history")

# 현재 브랜치
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# 오늘 작업일지 존재 여부
YEAR=$(date +%Y)
MONTH=$(date +%m-%B)
WORKLOG_PATH="work_logs/01_daily_logs/$YEAR/$MONTH/$TODAY.md"
if [ -f "$PROJECT_ROOT/$WORKLOG_PATH" ]; then
    WORKLOG_STATUS="exists"
else
    WORKLOG_STATUS="not_created"
fi

# 컨텍스트 파일 생성
cat > "$CONTEXT_FILE" << EOF
# Session Context - $TODAY ($WEEKDAY)

## Git Status
**Branch**: $CURRENT_BRANCH

### Recent Commits
\`\`\`
$RECENT_COMMITS
\`\`\`

## Work Log Status
- Today's log: $WORKLOG_STATUS
- Path: $WORKLOG_PATH

## Quick Commands
- \`/daily:standup\` - 팀 스탠드업
- \`/tools:context-restore\` - 전체 컨텍스트 복원
- \`/daily:daily-close\` - 하루 마무리

---
*Auto-generated by session-context hook*
EOF

# 세션 시작 로그 (선택적)
if [ -n "$SLACK_WEBHOOK_URL" ]; then
    curl -s -X POST "$SLACK_WEBHOOK_URL" \
        -H "Content-Type: application/json" \
        -d "{
            \"text\": \":sunrise: *Session Started* - $TODAY\\nBranch: \`$CURRENT_BRANCH\`\"
        }" > /dev/null 2>&1 &
fi

# Hook 응답
echo '{"continue": true}'
