#!/bin/bash
# Worklog Auto-update Hook
# 이벤트: SessionEnd
# 용도: 세션 종료 시 작업 내용 자동 요약 및 기록

set -e

# stdin에서 JSON 입력 읽기
INPUT=$(cat)

# 프로젝트 루트 디렉토리
PROJECT_ROOT=$(pwd)

# 오늘 날짜
TODAY=$(date +%Y-%m-%d)
YEAR=$(date +%Y)
MONTH=$(date +%m-%B)
TIME=$(date +%H:%M)

# 작업일지 경로
WORKLOG_DIR="$PROJECT_ROOT/work_logs/01_daily_logs/$YEAR/$MONTH"
WORKLOG_FILE="$WORKLOG_DIR/$TODAY.md"
SESSION_LOG="$PROJECT_ROOT/.claude/context/session_summary.md"

# 디렉토리 생성
mkdir -p "$WORKLOG_DIR"
mkdir -p "$PROJECT_ROOT/.claude/context"

# 세션 동안의 git 활동 요약
SESSION_COMMITS=$(git log --oneline --since="today" 2>/dev/null | head -10 || echo "No commits today")
FILES_CHANGED=$(git diff --stat HEAD~5 --name-only 2>/dev/null | head -10 || echo "")

# 세션 요약 파일 생성
cat > "$SESSION_LOG" << EOF
# Session Summary - $TODAY $TIME

## Commits This Session
\`\`\`
$SESSION_COMMITS
\`\`\`

## Files Modified
\`\`\`
$FILES_CHANGED
\`\`\`

---
*Auto-generated by worklog-update hook*
EOF

# 작업일지가 없으면 새로 생성
if [ ! -f "$WORKLOG_FILE" ]; then
    cat > "$WORKLOG_FILE" << EOF
# Daily Work Log - $TODAY

## Session Activity

### Commits
\`\`\`
$SESSION_COMMITS
\`\`\`

### Files Changed
\`\`\`
$FILES_CHANGED
\`\`\`

---
*Note: Use \`/daily:daily-log\` for detailed work log*
*Auto-created by session-end hook at $TIME*
EOF
fi

# 세션 종료 알림 (선택적)
if [ -n "$SLACK_WEBHOOK_URL" ]; then
    COMMIT_COUNT=$(echo "$SESSION_COMMITS" | grep -c "^" 2>/dev/null || echo "0")
    curl -s -X POST "$SLACK_WEBHOOK_URL" \
        -H "Content-Type: application/json" \
        -d "{
            \"text\": \":moon: *Session Ended* - $TIME\\nCommits today: $COMMIT_COUNT\"
        }" > /dev/null 2>&1 &
fi

# Hook 응답
echo '{"continue": true}'
